/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *nametype;

typedef struct namenode *namelist;

typedef struct {
	u_int namearray_len;
	struct namenode *namearray_val;
} namearray;

struct namenode {
	nametype name;
	namelist next;
};
typedef struct namenode namenode;

struct readdir_res {
	int errno;
	union {
		namelist list_0;
		namelist list_1;
	} readdir_res_u;
};
typedef struct readdir_res readdir_res;

#define MESSAGEPROG 0x20000001
#define PRINTMESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTMESSAGE 1
extern  int * printmessage_1(char **, CLIENT *);
extern  int * printmessage_1_svc(char **, struct svc_req *);
extern int messageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTMESSAGE 1
extern  int * printmessage_1();
extern  int * printmessage_1_svc();
extern int messageprog_1_freeresult ();
#endif /* K&R C */

#define MULTI_PROG 0x100000001
#define TWO_INT_VERS_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define TWO_INT 2
extern  int * two_int_1(int *, CLIENT *);
extern  int * two_int_1_svc(int *, struct svc_req *);
#define THREE_INT 3
extern  int * three_int_1(int *, CLIENT *);
extern  int * three_int_1_svc(int *, struct svc_req *);
#define FOUR_INT 4
extern  int * four_int_1(int *, CLIENT *);
extern  int * four_int_1_svc(int *, struct svc_req *);
extern int multi_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TWO_INT 2
extern  int * two_int_1();
extern  int * two_int_1_svc();
#define THREE_INT 3
extern  int * three_int_1();
extern  int * three_int_1_svc();
#define FOUR_INT 4
extern  int * four_int_1();
extern  int * four_int_1_svc();
extern int multi_prog_1_freeresult ();
#endif /* K&R C */
#define TWO_INT_VERS_2 2

#if defined(__STDC__) || defined(__cplusplus)
extern  int * two_int_2(int *, CLIENT *);
extern  int * two_int_2_svc(int *, struct svc_req *);
extern  int * three_int_2(int *, CLIENT *);
extern  int * three_int_2_svc(int *, struct svc_req *);
extern  int * four_int_2(int *, CLIENT *);
extern  int * four_int_2_svc(int *, struct svc_req *);
extern int multi_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  int * two_int_2();
extern  int * two_int_2_svc();
extern  int * three_int_2();
extern  int * three_int_2_svc();
extern  int * four_int_2();
extern  int * four_int_2_svc();
extern int multi_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_namelist (XDR *, namelist*);
extern  bool_t xdr_namearray (XDR *, namearray*);
extern  bool_t xdr_namenode (XDR *, namenode*);
extern  bool_t xdr_readdir_res (XDR *, readdir_res*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_namelist ();
extern bool_t xdr_namearray ();
extern bool_t xdr_namenode ();
extern bool_t xdr_readdir_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
